language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y linux-headers-`uname -r`
script:
  # let's do something simple first
  - make
  - make clean
